import type { PhoneticFeatures } from "./yumiRig";
import type { LocalizedText } from "./localizedText";

export type EnglishCategory = "vowel" | "consonant";

export type GuidancePoint = { label: LocalizedText; text: LocalizedText };

export interface EnglishSound {
  id: string;
  /** 卡片上顯示的符號（IPA） */
  symbol: string;
  title: string;
  /** 完整 IPA 記音 */
  ipa: string;
  category: EnglishCategory;
  /**
   * 這個音「自己」的示範詞，故意跟 examples 不重複，
   * 這樣按符號旁的喇叭跟按例字旁的喇叭聽到的絕對是不同的音檔／語句，
   * 不會讓使用者搞混「我剛剛聽到的是符號本身，還是某個例字」。
   */
  anchor: string;
  /** Browser TTS 使用的短發音提示 */
  soundText: string;
  /** 完整版發音說明——展開「More guidance」時顯示。依 appLanguage 顯示英文或中文 */
  tip: LocalizedText;
  /** 卡片預設顯示的 2-3 個短提示（嘴唇/氣流/聲帶等），從 tip 拆出來的摘要 */
  guidance: GuidancePoint[];
  /** 驅動 Yumi 嘴型/舌位/氣流/聲帶 rig 的語音學特徵——見 lib/pronunciation/yumiRig.ts */
  phonetics: PhoneticFeatures;
  examples: string[];
  /** 未來若有真人錄音，可填入音檔網址；目前留空會 fallback 到語音合成 */
  audio?: string;
}

export const englishSounds: EnglishSound[] = [
  // ── 子音 Consonants ──────────────────────────────────────────
  {
    id: "p",
    symbol: "p",
    title: "P",
    ipa: "/p/",
    category: "consonant",
    anchor: "Pop",
    soundText: "puh",
    tip: { english: "Press your lips together, then release quickly. Let a light puff of air out — your vocal cords don't vibrate.", "traditional-chinese": "雙唇緊閉後迅速放開，氣流輕輕吐出，聲帶不振動。" },
    guidance: [{ label: { english: "Lips", "traditional-chinese": "嘴唇" }, text: { english: "Press together, then release quickly", "traditional-chinese": "雙唇緊閉後迅速放開" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Let a light puff of air out", "traditional-chinese": "氣流輕輕吐出" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords don't vibrate", "traditional-chinese": "聲帶不振動" } }],
    phonetics: { manner: "stop", place: "bilabial", voiced: false, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.06, tongueRegion: "neutral", tongueHeight: 0.5, tongueFrontness: 0.5, contactZone: "lower_lip" },
    examples: ["Pen", "Cup", "Apple"],
  },
  {
    id: "b",
    symbol: "b",
    title: "B",
    ipa: "/b/",
    category: "consonant",
    anchor: "Baby",
    soundText: "buh",
    tip: { english: "Press your lips together, then release — same motion as p, but your vocal cords vibrate this time.", "traditional-chinese": "雙唇緊閉後放開，動作跟 p 一樣，但聲帶要振動。" },
    guidance: [{ label: { english: "Lips", "traditional-chinese": "嘴唇" }, text: { english: "Press together, then release", "traditional-chinese": "雙唇緊閉後放開" } }, { label: { english: "Note", "traditional-chinese": "重點提示" }, text: { english: "Same motion as p", "traditional-chinese": "動作跟 p 一樣" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "But vocal cords do vibrate", "traditional-chinese": "但聲帶要振動" } }],
    phonetics: { manner: "stop", place: "bilabial", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.06, tongueRegion: "neutral", tongueHeight: 0.5, tongueFrontness: 0.5, contactZone: "lower_lip" },
    examples: ["Bag", "Cab", "Rubber"],
  },
  {
    id: "t",
    symbol: "t",
    title: "T",
    ipa: "/t/",
    category: "consonant",
    anchor: "Tent",
    soundText: "tuh",
    tip: { english: "Touch your tongue tip to the ridge behind your upper teeth, then release with a puff of air. Vocal cords don't vibrate.", "traditional-chinese": "舌尖抵住上齒齦，放開時吐氣，聲帶不振動。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Tip touches the ridge behind your upper teeth", "traditional-chinese": "舌尖抵住上齒齦" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Release with a puff of air", "traditional-chinese": "放開時吐氣" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords don't vibrate", "traditional-chinese": "聲帶不振動" } }],
    phonetics: { manner: "stop", place: "alveolar", voiced: false, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "tip", tongueHeight: 0.75, tongueFrontness: 0.85, contactZone: "alveolar_ridge" },
    examples: ["Top", "Cat", "Butter"],
  },
  {
    id: "d",
    symbol: "d",
    title: "D",
    ipa: "/d/",
    category: "consonant",
    anchor: "Dad",
    soundText: "duh",
    tip: { english: "Touch your tongue tip to the ridge behind your upper teeth, then release with your vocal cords vibrating.", "traditional-chinese": "舌尖抵住上齒齦，放開時聲帶要振動。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Tip touches the ridge behind your upper teeth", "traditional-chinese": "舌尖抵住上齒齦" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords vibrate on release", "traditional-chinese": "放開時聲帶要振動" } }],
    phonetics: { manner: "stop", place: "alveolar", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "tip", tongueHeight: 0.75, tongueFrontness: 0.85, contactZone: "alveolar_ridge" },
    examples: ["Dog", "Bed", "Ladder"],
  },
  {
    id: "k",
    symbol: "k",
    title: "K",
    ipa: "/k/",
    category: "consonant",
    anchor: "Kite",
    soundText: "kuh",
    tip: { english: "Press the back of your tongue against your soft palate, then release with a puff of air. Vocal cords don't vibrate.", "traditional-chinese": "舌根抵住軟顎，放開時吐氣，聲帶不振動。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Back of tongue touches the soft palate", "traditional-chinese": "舌根抵住軟顎" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Release with a puff of air", "traditional-chinese": "放開時吐氣" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords don't vibrate", "traditional-chinese": "聲帶不振動" } }],
    phonetics: { manner: "stop", place: "velar", voiced: false, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "back", tongueHeight: 0.75, tongueFrontness: 0.15, contactZone: "velum" },
    examples: ["Cat", "Sky", "Duck"],
  },
  {
    id: "g",
    symbol: "g",
    title: "G",
    ipa: "/ɡ/",
    category: "consonant",
    anchor: "Game",
    soundText: "guh",
    tip: { english: "Press the back of your tongue against your soft palate, then release with your vocal cords vibrating.", "traditional-chinese": "舌根抵住軟顎，放開時聲帶要振動。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Back of tongue touches the soft palate", "traditional-chinese": "舌根抵住軟顎" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords vibrate on release", "traditional-chinese": "放開時聲帶要振動" } }],
    phonetics: { manner: "stop", place: "velar", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "back", tongueHeight: 0.75, tongueFrontness: 0.15, contactZone: "velum" },
    examples: ["Go", "Bag", "Bigger"],
  },
  {
    id: "f",
    symbol: "f",
    title: "F",
    ipa: "/f/",
    category: "consonant",
    anchor: "Fun",
    // Was "fff" — repeated-letter strings like this have no defined
    // pronunciation in a TTS engine's text-to-speech model; different
    // voices/browsers read them as three spelled-out letters, a garbled
    // buzz, or something else entirely, which is exactly the "sounds
    // wrong"/"reads an unrelated sound" behavior repeatedly reported here.
    // Reusing the sound's own anchor word (already a real, examples-
    // distinct word — see the EnglishSound.anchor doc comment) is what
    // th/sh/zh/ch/j/ng/w/y already do successfully; this brings the rest
    // of the continuant/nasal/liquid consonants in line with that.
    soundText: "fun",
    tip: { english: "Rest your upper teeth lightly on your lower lip. Push air out through the gap. Vocal cords don't vibrate.", "traditional-chinese": "上排牙齒輕觸下唇，氣流從縫隙擠出摩擦，聲帶不振動。" },
    guidance: [{ label: { english: "Lips", "traditional-chinese": "嘴唇" }, text: { english: "Upper teeth touch your lower lip", "traditional-chinese": "上排牙齒輕觸下唇" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Air squeezes out through the gap", "traditional-chinese": "氣流從縫隙擠出摩擦" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords don't vibrate", "traditional-chinese": "聲帶不振動" } }],
    phonetics: { manner: "fricative", place: "labiodental", voiced: false, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "neutral", tongueHeight: 0.5, tongueFrontness: 0.6, contactZone: "lower_lip" },
    examples: ["Fish", "Coffee", "Leaf"],
  },
  {
    id: "v",
    symbol: "v",
    title: "V",
    ipa: "/v/",
    category: "consonant",
    anchor: "Voice",
    soundText: "voice",
    tip: { english: "Same mouth position as f — upper teeth on lower lip — but this time your vocal cords vibrate.", "traditional-chinese": "動作跟 f 完全一樣（上齒觸下唇），差別是聲帶要振動。" },
    guidance: [{ label: { english: "Lips", "traditional-chinese": "嘴唇" }, text: { english: "Same as f (upper teeth on lower lip)", "traditional-chinese": "動作跟 f 完全一樣（上齒觸下唇）" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "The difference is your vocal cords vibrate", "traditional-chinese": "差別是聲帶要振動" } }],
    phonetics: { manner: "fricative", place: "labiodental", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "neutral", tongueHeight: 0.5, tongueFrontness: 0.6, contactZone: "lower_lip" },
    examples: ["Van", "Very", "Love"],
  },
  {
    id: "th-voiceless",
    symbol: "θ",
    title: "TH",
    ipa: "/θ/",
    category: "consonant",
    anchor: "Thanks",
    soundText: "think",
    tip: { english: "Poke your tongue tip gently between your upper and lower teeth, and push air out with friction. Vocal cords don't vibrate.", "traditional-chinese": "舌尖輕輕伸到上下齒之間，吐氣摩擦，聲帶不振動。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Tip pokes gently between your teeth", "traditional-chinese": "舌尖輕輕伸到上下齒之間" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Push air out with friction", "traditional-chinese": "吐氣摩擦" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords don't vibrate", "traditional-chinese": "聲帶不振動" } }],
    phonetics: { manner: "fricative", place: "dental", voiced: false, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.18, tongueRegion: "tip", tongueHeight: 0.6, tongueFrontness: 0.95, contactZone: "upper_teeth" },
    examples: ["Think", "Bath", "Three"],
  },
  {
    id: "th-voiced",
    symbol: "ð",
    title: "TH",
    ipa: "/ð/",
    category: "consonant",
    anchor: "Then",
    soundText: "this",
    tip: { english: "Same tongue position as θ, but your vocal cords vibrate this time.", "traditional-chinese": "舌位跟 θ 一樣，差別是聲帶要振動。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Same as θ", "traditional-chinese": "舌位跟 θ 一樣" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "The difference is your vocal cords vibrate", "traditional-chinese": "差別是聲帶要振動" } }],
    phonetics: { manner: "fricative", place: "dental", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.18, tongueRegion: "tip", tongueHeight: 0.6, tongueFrontness: 0.95, contactZone: "upper_teeth" },
    examples: ["This", "Mother", "Smooth"],
  },
  {
    id: "s",
    symbol: "s",
    title: "S",
    ipa: "/s/",
    category: "consonant",
    anchor: "Snake",
    soundText: "snake",
    tip: { english: "Bring your tongue tip close to the ridge behind your teeth and let air hiss out through the narrow gap. Vocal cords don't vibrate.", "traditional-chinese": "舌尖靠近齒齦，氣流從中間縫隙摩擦而出，聲帶不振動。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Tip near the ridge behind your teeth", "traditional-chinese": "舌尖靠近齒齦" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Air hisses out through a narrow gap", "traditional-chinese": "氣流從中間縫隙摩擦而出" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords don't vibrate", "traditional-chinese": "聲帶不振動" } }],
    phonetics: { manner: "fricative", place: "alveolar", voiced: false, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "tip", tongueHeight: 0.75, tongueFrontness: 0.85, contactZone: "alveolar_ridge" },
    examples: ["Sun", "Bus", "City"],
  },
  {
    id: "z",
    symbol: "z",
    title: "Z",
    ipa: "/z/",
    category: "consonant",
    anchor: "Zebra",
    soundText: "zebra",
    tip: { english: "Same tongue position as s, but your vocal cords vibrate — it should sound like a buzzing bee.", "traditional-chinese": "舌位跟 s 一樣，差別是聲帶要振動，像蜜蜂嗡嗡聲。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Same as s", "traditional-chinese": "舌位跟 s 一樣" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "The difference is your vocal cords vibrate", "traditional-chinese": "差別是聲帶要振動" } }, { label: { english: "Note", "traditional-chinese": "重點提示" }, text: { english: "Sounds like a buzzing bee", "traditional-chinese": "像蜜蜂嗡嗡聲" } }],
    phonetics: { manner: "fricative", place: "alveolar", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "tip", tongueHeight: 0.75, tongueFrontness: 0.85, contactZone: "alveolar_ridge" },
    examples: ["Zoo", "Buzz", "Rose"],
  },
  {
    id: "sh",
    symbol: "ʃ",
    title: "SH",
    ipa: "/ʃ/",
    category: "consonant",
    anchor: "Shop",
    soundText: "shop",
    tip: { english: "Bring the body of your tongue close to the front of your hard palate, push your lips forward slightly, and push air out with friction. Vocal cords don't vibrate.", "traditional-chinese": "舌面靠近硬顎前部，嘴唇微微前突，吐氣摩擦，聲帶不振動。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Body of tongue near the front of the hard palate", "traditional-chinese": "舌面靠近硬顎前部" } }, { label: { english: "Lips", "traditional-chinese": "嘴唇" }, text: { english: "Push forward slightly", "traditional-chinese": "嘴唇微微前突" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Push air out with friction; vocal cords don't vibrate", "traditional-chinese": "吐氣摩擦，聲帶不振動" } }],
    phonetics: { manner: "fricative", place: "postalveolar", voiced: false, aspirated: false, nasal: false, lipRounding: "slightly_rounded", jawOpening: 0.2, tongueRegion: "blade", tongueHeight: 0.7, tongueFrontness: 0.75, contactZone: "postalveolar_zone" },
    examples: ["Shoe", "Wish", "Nation"],
  },
  {
    id: "zh",
    symbol: "ʒ",
    title: "ZH",
    ipa: "/ʒ/",
    category: "consonant",
    anchor: "Genre",
    soundText: "measure",
    tip: { english: "Same tongue position as sh, but your vocal cords vibrate this time.", "traditional-chinese": "舌位跟 sh 一樣，差別是聲帶要振動。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Same as sh", "traditional-chinese": "舌位跟 sh 一樣" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "The difference is your vocal cords vibrate", "traditional-chinese": "差別是聲帶要振動" } }],
    phonetics: { manner: "fricative", place: "postalveolar", voiced: true, aspirated: false, nasal: false, lipRounding: "slightly_rounded", jawOpening: 0.2, tongueRegion: "blade", tongueHeight: 0.7, tongueFrontness: 0.75, contactZone: "postalveolar_zone" },
    examples: ["Measure", "Vision", "Beige"],
  },
  {
    id: "h",
    symbol: "h",
    title: "H",
    ipa: "/h/",
    category: "consonant",
    anchor: "House",
    soundText: "house",
    tip: { english: "Let air brush gently past your glottis, like breathing out a soft \"ha.\" Vocal cords don't vibrate.", "traditional-chinese": "聲門輕輕摩擦送氣，像哈氣一樣，聲帶不振動。" },
    guidance: [{ label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "A light friction at the glottis", "traditional-chinese": "聲門輕輕摩擦送氣" } }, { label: { english: "Note", "traditional-chinese": "重點提示" }, text: { english: "Like breathing out a soft \"ha\"", "traditional-chinese": "像哈氣一樣" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords don't vibrate", "traditional-chinese": "聲帶不振動" } }],
    phonetics: { manner: "fricative", place: "glottal", voiced: false, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.3, tongueRegion: "neutral", tongueHeight: 0.4, tongueFrontness: 0.5, contactZone: "none" },
    examples: ["Hat", "Hello", "Ahead"],
  },
  {
    id: "ch",
    symbol: "tʃ",
    title: "CH",
    ipa: "/tʃ/",
    category: "consonant",
    anchor: "Cheese",
    soundText: "church",
    tip: { english: "Combine t and sh in quick succession — it should read as one single sound, with a strong puff of air.", "traditional-chinese": "t 跟 sh 快速連續發出，像一個音。" },
    guidance: [{ label: { english: "How it's made", "traditional-chinese": "發音方式" }, text: { english: "t and sh fired quickly together", "traditional-chinese": "t 跟 sh 快速連續發出" } }, { label: { english: "Note", "traditional-chinese": "重點提示" }, text: { english: "Reads as one single sound", "traditional-chinese": "像一個音" } }],
    phonetics: { manner: "affricate", place: "postalveolar", voiced: false, aspirated: true, nasal: false, lipRounding: "slightly_rounded", jawOpening: 0.2, tongueRegion: "blade", tongueHeight: 0.7, tongueFrontness: 0.75, contactZone: "postalveolar_zone" },
    examples: ["Chair", "Watch", "Nature"],
  },
  {
    id: "j",
    symbol: "dʒ",
    title: "J",
    ipa: "/dʒ/",
    category: "consonant",
    anchor: "Giant",
    soundText: "judge",
    tip: { english: "Combine d and zh in quick succession, with your vocal cords vibrating.", "traditional-chinese": "d 跟 zh 快速連續發出，聲帶要振動。" },
    guidance: [{ label: { english: "How it's made", "traditional-chinese": "發音方式" }, text: { english: "d and zh fired quickly together", "traditional-chinese": "d 跟 zh 快速連續發出" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords vibrate", "traditional-chinese": "聲帶要振動" } }],
    phonetics: { manner: "affricate", place: "postalveolar", voiced: true, aspirated: false, nasal: false, lipRounding: "slightly_rounded", jawOpening: 0.2, tongueRegion: "blade", tongueHeight: 0.7, tongueFrontness: 0.75, contactZone: "postalveolar_zone" },
    examples: ["Jump", "Bridge", "Age"],
  },
  {
    id: "m",
    symbol: "m",
    title: "M",
    ipa: "/m/",
    category: "consonant",
    anchor: "Moon",
    soundText: "moon",
    tip: { english: "Close your lips, and let the air flow out through your nose instead. Vocal cords vibrate.", "traditional-chinese": "雙唇閉合，氣流改從鼻腔流出，聲帶振動。" },
    guidance: [{ label: { english: "Lips", "traditional-chinese": "嘴唇" }, text: { english: "Close together", "traditional-chinese": "雙唇閉合" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Air flows out through your nose instead", "traditional-chinese": "氣流改從鼻腔流出" } }, { label: { english: "Voicing", "traditional-chinese": "聲帶" }, text: { english: "Vocal cords vibrate", "traditional-chinese": "聲帶振動" } }],
    phonetics: { manner: "nasal", place: "bilabial", voiced: true, aspirated: false, nasal: true, lipRounding: "unrounded", jawOpening: 0.06, tongueRegion: "neutral", tongueHeight: 0.5, tongueFrontness: 0.5, contactZone: "lower_lip" },
    examples: ["Man", "Summer", "Time"],
  },
  {
    id: "n",
    symbol: "n",
    title: "N",
    ipa: "/n/",
    category: "consonant",
    anchor: "Nice",
    soundText: "nice",
    tip: { english: "Touch your tongue tip to the ridge behind your upper teeth, and let the air flow out through your nose instead.", "traditional-chinese": "舌尖抵住上齒齦，氣流改從鼻腔流出。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Tip touches the ridge behind your upper teeth", "traditional-chinese": "舌尖抵住上齒齦" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Air flows out through your nose instead", "traditional-chinese": "氣流改從鼻腔流出" } }],
    phonetics: { manner: "nasal", place: "alveolar", voiced: true, aspirated: false, nasal: true, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "tip", tongueHeight: 0.75, tongueFrontness: 0.85, contactZone: "alveolar_ridge" },
    examples: ["Nose", "Dinner", "Sun"],
  },
  {
    id: "ng",
    symbol: "ŋ",
    title: "NG",
    ipa: "/ŋ/",
    category: "consonant",
    anchor: "King",
    soundText: "sing",
    tip: { english: "Press the back of your tongue against your soft palate and let the air flow out through your nose. Don't add an extra g sound at the end.", "traditional-chinese": "舌根抵住軟顎，氣流改從鼻腔流出，不要加上額外的 g 音。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Back of tongue touches the soft palate", "traditional-chinese": "舌根抵住軟顎" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Air flows out through your nose instead", "traditional-chinese": "氣流改從鼻腔流出" } }, { label: { english: "Note", "traditional-chinese": "重點提示" }, text: { english: "Don't add an extra g sound", "traditional-chinese": "不要加上額外的 g 音" } }],
    phonetics: { manner: "nasal", place: "velar", voiced: true, aspirated: false, nasal: true, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "back", tongueHeight: 0.75, tongueFrontness: 0.15, contactZone: "velum" },
    examples: ["Sing", "Long", "Finger"],
  },
  {
    id: "l",
    symbol: "l",
    title: "L",
    ipa: "/l/",
    category: "consonant",
    anchor: "Love",
    soundText: "love",
    tip: { english: "Touch your tongue tip to the ridge behind your upper teeth, and let the air flow out around the sides of your tongue.", "traditional-chinese": "舌尖抵住上齒齦，氣流從舌頭兩側流出。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Tip touches the ridge behind your upper teeth", "traditional-chinese": "舌尖抵住上齒齦" } }, { label: { english: "Airflow", "traditional-chinese": "氣流" }, text: { english: "Air flows out around the sides of your tongue", "traditional-chinese": "氣流從舌頭兩側流出" } }],
    phonetics: { manner: "lateral", place: "alveolar", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "tip", tongueHeight: 0.75, tongueFrontness: 0.85, contactZone: "alveolar_ridge" },
    examples: ["Leg", "Ball", "Yellow"],
  },
  {
    id: "r",
    symbol: "r",
    title: "R",
    ipa: "/r/",
    category: "consonant",
    anchor: "Rain",
    soundText: "rain",
    tip: { english: "Curl your tongue tip back without letting it touch the roof of your mouth, and push your lips forward slightly.", "traditional-chinese": "舌尖往後捲但不碰上顎，嘴唇微微突出。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Tip curls back without touching the roof of your mouth", "traditional-chinese": "舌尖往後捲但不碰上顎" } }, { label: { english: "Lips", "traditional-chinese": "嘴唇" }, text: { english: "Push forward slightly", "traditional-chinese": "嘴唇微微突出" } }],
    // contactZone is "none" (not postalveolar_zone) on purpose: r curls the
    // tongue tip up *without touching* the roof of the mouth (that's what
    // makes it an approximant, not a stop/fricative) — see the tip in
    // `tip` above. A non-"none" zone here would trigger the rig's contact-
    // pulse animation, visually claiming a touch that never happens.
    phonetics: { manner: "approximant", place: "retroflex", voiced: true, aspirated: false, nasal: false, lipRounding: "slightly_rounded", jawOpening: 0.22, tongueRegion: "tip", tongueHeight: 0.6, tongueFrontness: 0.6, contactZone: "none" },
    examples: ["Red", "Car", "Very"],
  },
  {
    id: "w",
    symbol: "w",
    title: "W",
    ipa: "/w/",
    category: "consonant",
    anchor: "Wind",
    soundText: "wow",
    tip: { english: "Round your lips and push them forward, then relax quickly as you glide into the next vowel.", "traditional-chinese": "雙唇先圓起突出，再迅速放鬆滑向下一個母音。" },
    guidance: [{ label: { english: "Lips", "traditional-chinese": "嘴唇" }, text: { english: "Round and push forward first", "traditional-chinese": "雙唇先圓起突出" } }, { label: { english: "Glide", "traditional-chinese": "滑動" }, text: { english: "Then relax quickly into the next vowel", "traditional-chinese": "再迅速放鬆滑向下一個母音" } }],
    // contactZone "none" — w raises the tongue back *toward* the velum
    // (see `tip` above) without touching it; only lip rounding is a real
    // constriction here. See the r entry above for why this matters.
    phonetics: { manner: "approximant", place: "velar", voiced: true, aspirated: false, nasal: false, lipRounding: "strongly_rounded", jawOpening: 0.15, tongueRegion: "back", tongueHeight: 0.75, tongueFrontness: 0.15, contactZone: "none" },
    examples: ["Water", "Away", "Swim"],
  },
  {
    id: "y",
    symbol: "j",
    title: "Y",
    ipa: "/j/",
    category: "consonant",
    anchor: "You",
    soundText: "yes",
    tip: { english: "Bring the body of your tongue close to your hard palate for a brief moment, then glide straight into the next vowel.", "traditional-chinese": "舌面接近硬顎，短暫滑音後立刻滑向下一個母音。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Body of tongue close to the hard palate", "traditional-chinese": "舌面接近硬顎" } }, { label: { english: "Glide", "traditional-chinese": "滑動" }, text: { english: "A brief glide straight into the next vowel", "traditional-chinese": "短暫滑音後立刻滑向下一個母音" } }],
    // contactZone "none" — y brings the tongue body close to the hard
    // palate (see `tip` above) without touching it. See the r entry above
    // for why this matters.
    phonetics: { manner: "approximant", place: "palatal", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.2, tongueRegion: "front", tongueHeight: 0.8, tongueFrontness: 0.85, contactZone: "none" },
    examples: ["Yes", "Yellow", "Beyond"],
  },

  // ── 母音與雙母音 Vowels & Diphthongs ──────────────────────────
  {
    id: "iy",
    symbol: "iː",
    title: "長音 EE",
    ipa: "/iː/",
    category: "vowel",
    anchor: "Eat",
    soundText: "see",
    tip: { english: "Pull the corners of your mouth wide like a smile. Your tongue sits at its highest, most forward point. Hold the sound long.", "traditional-chinese": "嘴角向兩側拉開像微笑，舌位最高最前，音拉長。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Corners pulled wide, like a smile", "traditional-chinese": "嘴角向兩側拉開像微笑" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Highest and most forward", "traditional-chinese": "舌位最高最前" } }, { label: { english: "Length", "traditional-chinese": "長度" }, text: { english: "Held long", "traditional-chinese": "音拉長" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.15, tongueRegion: "middle", tongueHeight: 0.95, tongueFrontness: 0.95, contactZone: "none" },
    examples: ["See", "Sheep", "Key"],
  },
  {
    id: "ih",
    symbol: "ɪ",
    title: "短音 I",
    ipa: "/ɪ/",
    category: "vowel",
    anchor: "Fish",
    soundText: "sit",
    tip: { english: "Open your mouth corners only slightly. Your tongue sits a little lower and further back than for iː. Keep it short.", "traditional-chinese": "嘴角微張，舌位比 iː 略低略後，音短促。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Corners slightly open", "traditional-chinese": "嘴角微張" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "A little lower and further back than iː", "traditional-chinese": "舌位比 iː 略低略後" } }, { label: { english: "Length", "traditional-chinese": "長度" }, text: { english: "Short and relaxed", "traditional-chinese": "音短促" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.25, tongueRegion: "middle", tongueHeight: 0.8, tongueFrontness: 0.8, contactZone: "none" },
    examples: ["Sit", "Ship", "Big"],
  },
  {
    id: "ey",
    symbol: "eɪ",
    title: "長音 A（雙母音）",
    ipa: "/eɪ/",
    category: "vowel",
    anchor: "Eight",
    soundText: "say",
    tip: { english: "Glide quickly from an e mouth shape into an ɪ mouth shape.", "traditional-chinese": "從 e 的嘴形快速滑向 ɪ 的嘴形。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Glide quickly from an e shape to an ɪ shape", "traditional-chinese": "從 e 的嘴形快速滑向 ɪ 的嘴形" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.3, tongueRegion: "middle", tongueHeight: 0.78, tongueFrontness: 0.85, contactZone: "none" },
    examples: ["Say", "Cake", "Rain"],
  },
  {
    id: "eh",
    symbol: "ɛ",
    title: "短音 E",
    ipa: "/ɛ/",
    category: "vowel",
    anchor: "Egg",
    soundText: "bed",
    tip: { english: "Open your mouth about halfway. Your tongue sits mid-front — more relaxed than for iː.", "traditional-chinese": "嘴巴半開，舌位中前，比 iː 更放鬆。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Half open", "traditional-chinese": "嘴巴半開" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Mid-front", "traditional-chinese": "舌位中前" } }, { label: { english: "Note", "traditional-chinese": "重點提示" }, text: { english: "More relaxed than iː", "traditional-chinese": "比 iː 更放鬆" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.4, tongueRegion: "middle", tongueHeight: 0.6, tongueFrontness: 0.7, contactZone: "none" },
    examples: ["Bed", "Red", "Head"],
  },
  {
    id: "ae",
    symbol: "æ",
    title: "短音 A",
    ipa: "/æ/",
    category: "vowel",
    anchor: "Ant",
    soundText: "cat",
    tip: { english: "Open your mouth as wide as it goes. Your tongue sits low and forward — it should sound like a flattened \"a.\"", "traditional-chinese": "嘴巴張到最大，舌位低而靠前，像被壓扁的 a。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Open as wide as it goes", "traditional-chinese": "嘴巴張到最大" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Low and forward", "traditional-chinese": "舌位低而靠前" } }, { label: { english: "Note", "traditional-chinese": "重點提示" }, text: { english: "Sounds like a flattened \"a\"", "traditional-chinese": "像被壓扁的 a" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.9, tongueRegion: "middle", tongueHeight: 0.25, tongueFrontness: 0.75, contactZone: "none" },
    examples: ["Cat", "Bad", "Apple"],
  },
  {
    id: "ah",
    symbol: "ɑː",
    title: "長音 AH",
    ipa: "/ɑː/",
    category: "vowel",
    anchor: "Arm",
    soundText: "father",
    tip: { english: "Open your mouth wide. Your tongue sits low and back — like saying \"ah\" for the doctor.", "traditional-chinese": "嘴巴張大，舌位低而靠後，像看醫生說「啊」。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Open wide", "traditional-chinese": "嘴巴張大" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Low and back", "traditional-chinese": "舌位低而靠後" } }, { label: { english: "Note", "traditional-chinese": "重點提示" }, text: { english: "Like saying \"ah\" at the doctor's", "traditional-chinese": "像看醫生說「啊」" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.85, tongueRegion: "middle", tongueHeight: 0.15, tongueFrontness: 0.15, contactZone: "none" },
    examples: ["Father", "Car", "Palm"],
  },
  {
    id: "aw",
    symbol: "ɔː",
    title: "AW",
    ipa: "/ɔː/",
    category: "vowel",
    anchor: "Talk",
    soundText: "law",
    tip: { english: "Round your lips, opening your mouth more than for oʊ. Your tongue sits mid-back.", "traditional-chinese": "嘴唇成圓形，舌位中後，比 oʊ 嘴巴張更開。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Rounded lips, more open than oʊ", "traditional-chinese": "嘴唇成圓形，比 oʊ 嘴巴張更開" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Mid-back", "traditional-chinese": "舌位中後" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "rounded", jawOpening: 0.65, tongueRegion: "middle", tongueHeight: 0.35, tongueFrontness: 0.3, contactZone: "none" },
    examples: ["Thought", "Saw", "Ball"],
  },
  {
    id: "ow",
    symbol: "oʊ",
    title: "長音 O（雙母音）",
    ipa: "/oʊ/",
    category: "vowel",
    anchor: "Open",
    soundText: "go",
    tip: { english: "Glide from an o mouth shape toward ʊ, letting your lips gradually round.", "traditional-chinese": "從 o 的嘴形滑向 ʊ，嘴唇漸漸收圓。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Glide from o toward ʊ, lips gradually rounding", "traditional-chinese": "從 o 的嘴形滑向 ʊ，嘴唇漸漸收圓" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "rounded", jawOpening: 0.35, tongueRegion: "middle", tongueHeight: 0.6, tongueFrontness: 0.25, contactZone: "none" },
    examples: ["Go", "Boat", "Home"],
  },
  {
    id: "uh-short",
    symbol: "ʊ",
    title: "短音 OO",
    ipa: "/ʊ/",
    category: "vowel",
    anchor: "Wood",
    soundText: "book",
    tip: { english: "Round your lips slightly. Your tongue sits high and back. Keep it short and relaxed.", "traditional-chinese": "嘴唇微圓，舌位高而靠後，音短促、放鬆。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Lips slightly rounded", "traditional-chinese": "嘴唇微圓" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "High and back", "traditional-chinese": "舌位高而靠後" } }, { label: { english: "Length", "traditional-chinese": "長度" }, text: { english: "Short and relaxed", "traditional-chinese": "音短促、放鬆" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "slightly_rounded", jawOpening: 0.3, tongueRegion: "middle", tongueHeight: 0.75, tongueFrontness: 0.15, contactZone: "none" },
    examples: ["Book", "Foot", "Put"],
  },
  {
    id: "oo-long",
    symbol: "uː",
    title: "長音 OO",
    ipa: "/uː/",
    category: "vowel",
    anchor: "Choose",
    soundText: "food",
    tip: { english: "Round your lips tightly and push them forward. Your tongue sits at its highest, furthest-back point. Hold the sound long.", "traditional-chinese": "嘴唇緊緊收圓突出，舌位最高最後，音拉長。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Lips tightly rounded and pushed forward", "traditional-chinese": "嘴唇緊緊收圓突出" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Highest and furthest back", "traditional-chinese": "舌位最高最後" } }, { label: { english: "Length", "traditional-chinese": "長度" }, text: { english: "Held long", "traditional-chinese": "音拉長" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "strongly_rounded", jawOpening: 0.2, tongueRegion: "middle", tongueHeight: 0.9, tongueFrontness: 0.05, contactZone: "none" },
    examples: ["Food", "Blue", "Moon"],
  },
  {
    id: "uh",
    symbol: "ʌ",
    title: "短音 U",
    ipa: "/ʌ/",
    category: "vowel",
    anchor: "Up",
    soundText: "cup",
    tip: { english: "Open your mouth about halfway, lips relaxed and not rounded. Your tongue sits central, slightly back. Keep it short.", "traditional-chinese": "嘴巴半開，不圓唇，舌位中央偏後，音短促。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Half open, lips not rounded", "traditional-chinese": "嘴巴半開，不圓唇" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Central, slightly back", "traditional-chinese": "舌位中央偏後" } }, { label: { english: "Length", "traditional-chinese": "長度" }, text: { english: "Short", "traditional-chinese": "音短促" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.45, tongueRegion: "middle", tongueHeight: 0.5, tongueFrontness: 0.4, contactZone: "none" },
    examples: ["Cup", "Sun", "Love"],
  },
  {
    id: "er-stressed",
    symbol: "ɜːr",
    title: "重音 ER",
    ipa: "/ɜːr/",
    category: "vowel",
    anchor: "Girl",
    soundText: "bird",
    tip: { english: "Curl your tongue tip up without touching the roof of your mouth, keeping it central. Hold the sound long.", "traditional-chinese": "舌尖往上捲但不碰上顎，舌位中央，音拉長。" },
    guidance: [{ label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Tip curls up without touching the roof of your mouth, central", "traditional-chinese": "舌尖往上捲但不碰上顎，舌位中央" } }, { label: { english: "Length", "traditional-chinese": "長度" }, text: { english: "Held long", "traditional-chinese": "音拉長" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "slightly_rounded", jawOpening: 0.4, tongueRegion: "middle", tongueHeight: 0.55, tongueFrontness: 0.45, contactZone: "none" },
    examples: ["Bird", "Her", "Learn"],
  },
  {
    id: "schwa",
    symbol: "ə",
    title: "弱母音 Schwa",
    ipa: "/ə/",
    category: "vowel",
    anchor: "Again",
    soundText: "about",
    tip: { english: "Relax your lips completely. Your tongue sits central and neutral — this is the most common unstressed vowel in English.", "traditional-chinese": "嘴唇完全放鬆，舌位中央，英文裡最常出現的非重音母音。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Completely relaxed", "traditional-chinese": "嘴唇完全放鬆" } }, { label: { english: "Tongue position", "traditional-chinese": "舌位" }, text: { english: "Central", "traditional-chinese": "舌位中央" } }, { label: { english: "Note", "traditional-chinese": "重點提示" }, text: { english: "The most common unstressed vowel in English", "traditional-chinese": "英文裡最常出現的非重音母音" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.35, tongueRegion: "middle", tongueHeight: 0.5, tongueFrontness: 0.5, contactZone: "none" },
    examples: ["About", "Sofa", "Banana"],
  },
  {
    id: "ay",
    symbol: "aɪ",
    title: "長音 I（雙母音）",
    ipa: "/aɪ/",
    category: "vowel",
    anchor: "Ice",
    soundText: "eye",
    tip: { english: "Glide quickly from an a mouth shape to an ɪ mouth shape.", "traditional-chinese": "從 a 的嘴形快速滑向 ɪ。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Glide quickly from a to ɪ", "traditional-chinese": "從 a 的嘴形快速滑向 ɪ" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "unrounded", jawOpening: 0.7, tongueRegion: "middle", tongueHeight: 0.4, tongueFrontness: 0.5, contactZone: "none" },
    examples: ["My", "Time", "Light"],
  },
  {
    id: "ow-diphthong",
    symbol: "aʊ",
    title: "OW（雙母音）",
    ipa: "/aʊ/",
    category: "vowel",
    anchor: "Out",
    soundText: "cow",
    tip: { english: "Glide quickly from an a mouth shape toward ʊ, letting your lips gradually round.", "traditional-chinese": "從 a 的嘴形快速滑向 ʊ，嘴唇漸漸收圓。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Glide from a toward ʊ, lips gradually rounding", "traditional-chinese": "從 a 的嘴形快速滑向 ʊ，嘴唇漸漸收圓" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "slightly_rounded", jawOpening: 0.65, tongueRegion: "middle", tongueHeight: 0.4, tongueFrontness: 0.4, contactZone: "none" },
    examples: ["How", "Now", "Cloud"],
  },
  {
    id: "oy",
    symbol: "ɔɪ",
    title: "OY（雙母音）",
    ipa: "/ɔɪ/",
    category: "vowel",
    anchor: "Oil",
    soundText: "boy",
    tip: { english: "Glide quickly from an ɔ mouth shape to an ɪ mouth shape.", "traditional-chinese": "從 ɔ 的嘴形快速滑向 ɪ。" },
    guidance: [{ label: { english: "Mouth shape", "traditional-chinese": "嘴型" }, text: { english: "Glide quickly from ɔ to ɪ", "traditional-chinese": "從 ɔ 的嘴形快速滑向 ɪ" } }],
    phonetics: { manner: "vowel", place: "none", voiced: true, aspirated: false, nasal: false, lipRounding: "slightly_rounded", jawOpening: 0.55, tongueRegion: "middle", tongueHeight: 0.5, tongueFrontness: 0.5, contactZone: "none" },
    examples: ["Boy", "Toy", "Voice"],
  },
];
