export type EnglishCategory = "vowel" | "consonant";

export interface EnglishSound {
  id: string;
  /** 卡片上顯示的符號（IPA） */
  symbol: string;
  title: string;
  /** 完整 IPA 記音 */
  ipa: string;
  category: EnglishCategory;
  /**
   * 這個音「自己」的示範詞，故意跟 examples 不重複，
   * 這樣按符號旁的喇叭跟按例字旁的喇叭聽到的絕對是不同的音檔／語句，
   * 不會讓使用者搞混「我剛剛聽到的是符號本身，還是某個例字」。
   */
  anchor: string;
  /** Browser TTS 使用的短發音提示 */
  soundText: string;
  tip: string;
  examples: string[];
  /** 未來若有真人錄音，可填入音檔網址；目前留空會 fallback 到語音合成 */
  audio?: string;
}

export const englishSounds: EnglishSound[] = [
  // ── 子音 Consonants ──────────────────────────────────────────
  {
    id: "p",
    symbol: "p",
    title: "P — 不送氣清音",
    ipa: "/p/",
    category: "consonant",
    anchor: "Pop",
    soundText: "puh",
    tip: "雙唇緊閉後迅速放開，氣流輕輕吐出，聲帶不振動。",
    examples: ["Pen", "Cup", "Apple"],
  },
  {
    id: "b",
    symbol: "b",
    title: "B — 濁音 P",
    ipa: "/b/",
    category: "consonant",
    anchor: "Baby",
    soundText: "buh",
    tip: "雙唇緊閉後放開，動作跟 p 一樣，但聲帶要振動。",
    examples: ["Bag", "Cab", "Rubber"],
  },
  {
    id: "t",
    symbol: "t",
    title: "T — 不送氣清音",
    ipa: "/t/",
    category: "consonant",
    anchor: "Tent",
    soundText: "tuh",
    tip: "舌尖抵住上齒齦，放開時吐氣，聲帶不振動。",
    examples: ["Top", "Cat", "Butter"],
  },
  {
    id: "d",
    symbol: "d",
    title: "D — 濁音 T",
    ipa: "/d/",
    category: "consonant",
    anchor: "Dad",
    soundText: "duh",
    tip: "舌尖抵住上齒齦，放開時聲帶要振動。",
    examples: ["Dog", "Bed", "Ladder"],
  },
  {
    id: "k",
    symbol: "k",
    title: "K — 不送氣清音",
    ipa: "/k/",
    category: "consonant",
    anchor: "Kite",
    soundText: "kuh",
    tip: "舌根抵住軟顎，放開時吐氣，聲帶不振動。",
    examples: ["Cat", "Sky", "Duck"],
  },
  {
    id: "g",
    symbol: "g",
    title: "G — 濁音 K",
    ipa: "/ɡ/",
    category: "consonant",
    anchor: "Game",
    soundText: "guh",
    tip: "舌根抵住軟顎，放開時聲帶要振動。",
    examples: ["Go", "Bag", "Bigger"],
  },
  {
    id: "f",
    symbol: "f",
    title: "F — 唇齒清擦音",
    ipa: "/f/",
    category: "consonant",
    anchor: "Fun",
    soundText: "fff",
    tip: "上排牙齒輕觸下唇，氣流從縫隙擠出摩擦，聲帶不振動。",
    examples: ["Fish", "Coffee", "Leaf"],
  },
  {
    id: "v",
    symbol: "v",
    title: "V — 唇齒濁擦音",
    ipa: "/v/",
    category: "consonant",
    anchor: "Voice",
    soundText: "vvv",
    tip: "動作跟 f 完全一樣（上齒觸下唇），差別是聲帶要振動。",
    examples: ["Van", "Very", "Love"],
  },
  {
    id: "th-voiceless",
    symbol: "θ",
    title: "TH — 清音",
    ipa: "/θ/",
    category: "consonant",
    anchor: "Thanks",
    soundText: "think",
    tip: "舌尖輕輕伸到上下齒之間，吐氣摩擦，聲帶不振動。",
    examples: ["Think", "Bath", "Three"],
  },
  {
    id: "th-voiced",
    symbol: "ð",
    title: "TH — 濁音",
    ipa: "/ð/",
    category: "consonant",
    anchor: "Then",
    soundText: "this",
    tip: "舌位跟 θ 一樣，差別是聲帶要振動。",
    examples: ["This", "Mother", "Smooth"],
  },
  {
    id: "s",
    symbol: "s",
    title: "S — 清擦音",
    ipa: "/s/",
    category: "consonant",
    anchor: "Snake",
    soundText: "sss",
    tip: "舌尖靠近齒齦，氣流從中間縫隙摩擦而出，聲帶不振動。",
    examples: ["Sun", "Bus", "City"],
  },
  {
    id: "z",
    symbol: "z",
    title: "Z — 濁音 S",
    ipa: "/z/",
    category: "consonant",
    anchor: "Zebra",
    soundText: "zzz",
    tip: "舌位跟 s 一樣，差別是聲帶要振動，像蜜蜂嗡嗡聲。",
    examples: ["Zoo", "Buzz", "Rose"],
  },
  {
    id: "sh",
    symbol: "ʃ",
    title: "SH — 清擦音",
    ipa: "/ʃ/",
    category: "consonant",
    anchor: "Shop",
    soundText: "shhh",
    tip: "舌面靠近硬顎前部，嘴唇微微前突，吐氣摩擦，聲帶不振動。",
    examples: ["Shoe", "Wish", "Nation"],
  },
  {
    id: "zh",
    symbol: "ʒ",
    title: "ZH — 濁音 SH",
    ipa: "/ʒ/",
    category: "consonant",
    anchor: "Genre",
    soundText: "measure",
    tip: "舌位跟 sh 一樣，差別是聲帶要振動。",
    examples: ["Measure", "Vision", "Beige"],
  },
  {
    id: "h",
    symbol: "h",
    title: "H — 喉擦音",
    ipa: "/h/",
    category: "consonant",
    anchor: "House",
    soundText: "hhh",
    tip: "聲門輕輕摩擦送氣，像哈氣一樣，聲帶不振動。",
    examples: ["Hat", "Hello", "Ahead"],
  },
  {
    id: "ch",
    symbol: "tʃ",
    title: "CH — 塞擦音",
    ipa: "/tʃ/",
    category: "consonant",
    anchor: "Cheese",
    soundText: "church",
    tip: "t 跟 sh 快速連續發出，像一個音。",
    examples: ["Chair", "Watch", "Nature"],
  },
  {
    id: "j",
    symbol: "dʒ",
    title: "J — 濁音 CH",
    ipa: "/dʒ/",
    category: "consonant",
    anchor: "Giant",
    soundText: "judge",
    tip: "d 跟 zh 快速連續發出，聲帶要振動。",
    examples: ["Jump", "Bridge", "Age"],
  },
  {
    id: "m",
    symbol: "m",
    title: "M — 雙唇鼻音",
    ipa: "/m/",
    category: "consonant",
    anchor: "Moon",
    soundText: "mmm",
    tip: "雙唇閉合，氣流改從鼻腔流出，聲帶振動。",
    examples: ["Man", "Summer", "Time"],
  },
  {
    id: "n",
    symbol: "n",
    title: "N — 齒齦鼻音",
    ipa: "/n/",
    category: "consonant",
    anchor: "Nice",
    soundText: "nnn",
    tip: "舌尖抵住上齒齦，氣流改從鼻腔流出。",
    examples: ["Nose", "Dinner", "Sun"],
  },
  {
    id: "ng",
    symbol: "ŋ",
    title: "NG — 軟顎鼻音",
    ipa: "/ŋ/",
    category: "consonant",
    anchor: "King",
    soundText: "sing",
    tip: "舌根抵住軟顎，氣流改從鼻腔流出，不要加上額外的 g 音。",
    examples: ["Sing", "Long", "Finger"],
  },
  {
    id: "l",
    symbol: "l",
    title: "L — 邊音",
    ipa: "/l/",
    category: "consonant",
    anchor: "Love",
    soundText: "lll",
    tip: "舌尖抵住上齒齦，氣流從舌頭兩側流出。",
    examples: ["Leg", "Ball", "Yellow"],
  },
  {
    id: "r",
    symbol: "r",
    title: "R — 捲舌音",
    ipa: "/r/",
    category: "consonant",
    anchor: "Rain",
    soundText: "rrr",
    tip: "舌尖往後捲但不碰上顎，嘴唇微微突出。",
    examples: ["Red", "Car", "Very"],
  },
  {
    id: "w",
    symbol: "w",
    title: "W — 半母音",
    ipa: "/w/",
    category: "consonant",
    anchor: "Wind",
    soundText: "wow",
    tip: "雙唇先圓起突出，再迅速放鬆滑向下一個母音。",
    examples: ["Water", "Away", "Swim"],
  },
  {
    id: "y",
    symbol: "j",
    title: "Y — 半母音",
    ipa: "/j/",
    category: "consonant",
    anchor: "You",
    soundText: "yes",
    tip: "舌面接近硬顎，短暫滑音後立刻滑向下一個母音。",
    examples: ["Yes", "Yellow", "Beyond"],
  },

  // ── 母音與雙母音 Vowels & Diphthongs ──────────────────────────
  {
    id: "iy",
    symbol: "iː",
    title: "長音 EE",
    ipa: "/iː/",
    category: "vowel",
    anchor: "Eat",
    soundText: "see",
    tip: "嘴角向兩側拉開像微笑，舌位最高最前，音拉長。",
    examples: ["See", "Sheep", "Key"],
  },
  {
    id: "ih",
    symbol: "ɪ",
    title: "短音 I",
    ipa: "/ɪ/",
    category: "vowel",
    anchor: "Fish",
    soundText: "sit",
    tip: "嘴角微張，舌位比 iː 略低略後，音短促。",
    examples: ["Sit", "Ship", "Big"],
  },
  {
    id: "ey",
    symbol: "eɪ",
    title: "長音 A（雙母音）",
    ipa: "/eɪ/",
    category: "vowel",
    anchor: "Eight",
    soundText: "say",
    tip: "從 e 的嘴形快速滑向 ɪ 的嘴形。",
    examples: ["Say", "Cake", "Rain"],
  },
  {
    id: "eh",
    symbol: "ɛ",
    title: "短音 E",
    ipa: "/ɛ/",
    category: "vowel",
    anchor: "Egg",
    soundText: "bed",
    tip: "嘴巴半開，舌位中前，比 iː 更放鬆。",
    examples: ["Bed", "Red", "Head"],
  },
  {
    id: "ae",
    symbol: "æ",
    title: "短音 A",
    ipa: "/æ/",
    category: "vowel",
    anchor: "Ant",
    soundText: "cat",
    tip: "嘴巴張到最大，舌位低而靠前，像被壓扁的 a。",
    examples: ["Cat", "Bad", "Apple"],
  },
  {
    id: "ah",
    symbol: "ɑː",
    title: "長音 AH",
    ipa: "/ɑː/",
    category: "vowel",
    anchor: "Arm",
    soundText: "father",
    tip: "嘴巴張大，舌位低而靠後，像看醫生說「啊」。",
    examples: ["Father", "Car", "Palm"],
  },
  {
    id: "aw",
    symbol: "ɔː",
    title: "AW",
    ipa: "/ɔː/",
    category: "vowel",
    anchor: "Talk",
    soundText: "law",
    tip: "嘴唇成圓形，舌位中後，比 oʊ 嘴巴張更開。",
    examples: ["Thought", "Saw", "Ball"],
  },
  {
    id: "ow",
    symbol: "oʊ",
    title: "長音 O（雙母音）",
    ipa: "/oʊ/",
    category: "vowel",
    anchor: "Open",
    soundText: "go",
    tip: "從 o 的嘴形滑向 ʊ，嘴唇漸漸收圓。",
    examples: ["Go", "Boat", "Home"],
  },
  {
    id: "uh-short",
    symbol: "ʊ",
    title: "短音 OO",
    ipa: "/ʊ/",
    category: "vowel",
    anchor: "Wood",
    soundText: "book",
    tip: "嘴唇微圓，舌位高而靠後，音短促、放鬆。",
    examples: ["Book", "Foot", "Put"],
  },
  {
    id: "oo-long",
    symbol: "uː",
    title: "長音 OO",
    ipa: "/uː/",
    category: "vowel",
    anchor: "Choose",
    soundText: "food",
    tip: "嘴唇緊緊收圓突出，舌位最高最後，音拉長。",
    examples: ["Food", "Blue", "Moon"],
  },
  {
    id: "uh",
    symbol: "ʌ",
    title: "短音 U",
    ipa: "/ʌ/",
    category: "vowel",
    anchor: "Up",
    soundText: "cup",
    tip: "嘴巴半開，不圓唇，舌位中央偏後，音短促。",
    examples: ["Cup", "Sun", "Love"],
  },
  {
    id: "er-stressed",
    symbol: "ɜːr",
    title: "重音 ER",
    ipa: "/ɜːr/",
    category: "vowel",
    anchor: "Girl",
    soundText: "bird",
    tip: "舌尖往上捲但不碰上顎，舌位中央，音拉長。",
    examples: ["Bird", "Her", "Learn"],
  },
  {
    id: "schwa",
    symbol: "ə",
    title: "弱母音 Schwa",
    ipa: "/ə/",
    category: "vowel",
    anchor: "Again",
    soundText: "about",
    tip: "嘴唇完全放鬆，舌位中央，英文裡最常出現的非重音母音。",
    examples: ["About", "Sofa", "Banana"],
  },
  {
    id: "ay",
    symbol: "aɪ",
    title: "長音 I（雙母音）",
    ipa: "/aɪ/",
    category: "vowel",
    anchor: "Ice",
    soundText: "eye",
    tip: "從 a 的嘴形快速滑向 ɪ。",
    examples: ["My", "Time", "Light"],
  },
  {
    id: "ow-diphthong",
    symbol: "aʊ",
    title: "OW（雙母音）",
    ipa: "/aʊ/",
    category: "vowel",
    anchor: "Out",
    soundText: "cow",
    tip: "從 a 的嘴形快速滑向 ʊ，嘴唇漸漸收圓。",
    examples: ["How", "Now", "Cloud"],
  },
  {
    id: "oy",
    symbol: "ɔɪ",
    title: "OY（雙母音）",
    ipa: "/ɔɪ/",
    category: "vowel",
    anchor: "Oil",
    soundText: "boy",
    tip: "從 ɔ 的嘴形快速滑向 ɪ。",
    examples: ["Boy", "Toy", "Voice"],
  },
];
