import { render } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import {
  SUPPORTED_PROFILE_LANGUAGE_PAIRS,
  canLeadIn,
} from "@/lib/languages";

/* =========================================================
   Which two languages a screen may render

   The rule the whole app now turns on: the lead is the language being
   learned, the gloss is the profile's native language, and nothing else appears
   anywhere. A reader who switched to Italian and kept being shown English
   was watching a fallback quietly overrule a setting.
   ========================================================= */

/*
 * There is no "resolve which languages to show" step any more, and that is
 * the fix rather than a simplification of it.
 *
 * The old helper took the reader's two languages and appended whatever else
 * the content carried, which is how an Italian learner kept being shown
 * English. Filtering it to only the languages present fixed that and broke
 * something worse: it could return one language, or none, and every caller
 * destructures a pair and calls getLanguage() on both halves — so a card
 * missing one of the reader's languages crashed the screen it was on. The
 * messages page went white for exactly that reason.
 *
 * The pair is now decided by the reader alone and always has two members.
 * Whether the content has anything to put in them is a separate question,
 * asked by canLeadIn before an item is served and answered by `?? ""` when
 * it is rendered.
 */

describe("canLeadIn", () => {
  it("is the one question a feed has to ask", () => {
    expect(canLeadIn({ it: "Prigioni" }, "it")).toBe(true);
    expect(canLeadIn({ en: "Prisons" }, "it")).toBe(false);
    expect(canLeadIn({ it: "  " }, "it")).toBe(false);
  });
});

/* =========================================================
   The gloss follows the profile's native language
   ========================================================= */

const preferences = vi.hoisted(() => ({ interfaceLanguage: "english" }));
const profile = vi.hoisted(() => ({ learning: "it", native: "en" }));

vi.mock("@/hooks/preferences/useInterfaceLanguage", () => ({
  default: () => preferences.interfaceLanguage,
}));

vi.mock("@/contexts/LearningLanguageContext", () => ({
  useLearningLanguageContext: () => ({
    learningLanguage: profile.learning,
    nativeLanguage: profile.native,
  }),
}));

const { default: useDisplayLanguages } = await import(
  "@/hooks/useDisplayLanguages"
);

function read() {
  let result: ReturnType<typeof useDisplayLanguages> | null = null;

  function Probe() {
    result = useDisplayLanguages();
    return null;
  }

  render(<Probe />);
  return result!;
}

describe("useDisplayLanguages", () => {
  it("keeps the selected learning → native pair when the interface differs", () => {
    profile.learning = "it";
    profile.native = "en";
    preferences.interfaceLanguage = "french";

    expect(read().pair).toEqual(["it", "en"]);
  });

  it("puts the language being learned first, always", () => {
    profile.learning = "es";
    profile.native = "en";
    preferences.interfaceLanguage = "traditional-chinese";

    const { learningLanguage, pair } = read();

    expect(learningLanguage).toBe("es");
    expect(pair).toEqual(["es", "en"]);
  });

  it("uses the interface only as recovery when profile values collide", () => {
    profile.learning = "it";
    profile.native = "it";
    preferences.interfaceLanguage = "french";

    expect(read().pair).toEqual(["it", "fr"]);
  });

  it("never returns the same language twice, even when all three agree", () => {
    profile.learning = "en";
    profile.native = "en";
    preferences.interfaceLanguage = "english";

    const [primary, secondary] = read().pair;

    expect(primary).toBe("en");
    expect(secondary).not.toBe("en");
  });
});

/* =========================================================
   The same rule on the server

   Cards are generated by prompts that take a pair, and rendered by screens
   that resolve one. When those two disagree, a photo taken by a reader with
   a French interface comes back glossed in English and then has nowhere it
   can be shown. One rule, both sides.
   ========================================================= */

const { toLearningPair } = await import("@/lib/profile/languagePair");

describe("toLearningPair", () => {
  it("preserves every one of the 20 supported directions", () => {
    for (const [learning, native] of SUPPORTED_PROFILE_LANGUAGE_PAIRS) {
      expect(toLearningPair(learning, native, "italian")).toEqual([
        learning,
        native,
      ]);
    }
  });

  it("glosses in the profile's native language, like the screens do", () => {
    expect(toLearningPair("it", "en", "french")).toEqual(["it", "en"]);
  });

  it("agrees with useDisplayLanguages given the same profile", () => {
    profile.learning = "es";
    profile.native = "en";
    preferences.interfaceLanguage = "traditional-chinese";

    expect(toLearningPair("es", "en", "traditional-chinese")).toEqual(
      [...read().pair],
    );
  });

  it("keeps the native language when the app is in the one being learned", () => {
    expect(toLearningPair("fr", "zh-TW", "french")).toEqual(["fr", "zh-TW"]);
  });

  it("never returns a pair of one language", () => {
    expect(toLearningPair("en", "en", "english")).toEqual(["en", "zh-TW"]);
  });

  it("ignores a stored interface value that is not a language", () => {
    expect(toLearningPair("it", "zh-TW", "constructor")).toEqual(["it", "zh-TW"]);
    expect(toLearningPair("it", "zh-TW", undefined)).toEqual(["it", "zh-TW"]);
  });
});
