/** Publisher metadata is owned by the feed adapter, never generated by AI. */
export type NewsArticle = {
  category: string;
  sourceName: string;
  title: string;
  url: string;
  publishedAt: string;
  excerpt: string;
  imageUrl: string | null;
};

export type RssSource = {
  name: string;
  url: string;
  articleHosts: readonly string[];
  imageHosts: readonly string[];
  excludeCategories?: readonly string[];
  includeCategories?: readonly string[];
  minimumExcerptLength?: number;
};

export const RSS_SOURCES = {
  hyperallergic: {
    name: "Hyperallergic", url: "https://hyperallergic.com/rss/",
    articleHosts: ["hyperallergic.com"], imageHosts: ["storage.ghost.io"],
  },
  artnews: {
    name: "ARTnews", url: "https://www.artnews.com/feed/",
    articleHosts: ["www.artnews.com", "artnews.com"], imageHosts: ["www.artnews.com"],
  },
  ars: {
    name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/technology-lab",
    articleHosts: ["arstechnica.com"], imageHosts: ["cdn.arstechnica.net"],
  },
  vogue: {
    name: "Vogue", url: "https://www.vogue.com/feed/rss",
    articleHosts: ["www.vogue.com"], imageHosts: ["assets.vogue.com"],
    excludeCategories: ["Shopping", "Beauty", "Living", "Weddings", "Horoscope"],
    includeCategories: ["Fashion", "Runway", "Business"],
  },
  fashionunited: {
    name: "FashionUnited", url: "https://fashionunited.com/rss/news?local_newsboard=us",
    articleHosts: ["fashionunited.com"], imageHosts: ["r.fashionunited.com"],
    minimumExcerptLength: 350,
  },
} as const satisfies Record<string, RssSource>;

export type NewsSlot = {
  category: string;
  section?: string;
  query?: string;
  headlineMustMention?: string[];
  rss?: RssSource;
};

/** Twelve cards, still at most four model batches; focused topics go first. */
export const NEWS_SLOTS: NewsSlot[] = [
  { category: "Art", rss: RSS_SOURCES.hyperallergic },
  { category: "Technology", rss: RSS_SOURCES.ars },
  { category: "Fashion", rss: RSS_SOURCES.vogue },
  { category: "Art", rss: RSS_SOURCES.artnews },
  { category: "Technology", section: "technology" },
  { category: "Fashion", rss: RSS_SOURCES.fashionunited },
  { category: "Art", section: "artanddesign" },
  { category: "Fashion", section: "fashion" },
  { category: "World", section: "world" },
  { category: "Science", section: "science" },
  { category: "Environment", section: "environment" },
  { category: "Taiwan", query: "Taiwan", headlineMustMention: ["taiwan", "taipei", "taiwanese"] },
];
