/**
 * Writes every file that carries the Exchange Notes logo.
 *
 *   npm run generate:brand
 *
 * The brand asset tree under public/brand, the favicon and app icons in app/,
 * and the PWA icons the manifest points at are all generated — none of them
 * is hand-drawn. Change a number in lib/brand/exchangeNotesLogo.ts, run this,
 * and every surface the mark appears on moves together. Editing one of the
 * output files by hand puts that surface out of step with the rest until the
 * next run silently overwrites it.
 *
 * This is §28's pipeline: one geometry, one canonical SVG, one React
 * component, light/dark colour tokens, and automated raster exports from the
 * same source.
 *
 * Rasterising uses sharp, which reaches this project as one of Next's own
 * dependencies and is declared in devDependencies so that this script does
 * not quietly depend on someone else's install tree.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

import {
  renderAppIconSvg,
  renderFaviconSvg,
  renderLogoSvg,
} from "../lib/brand/exchangeNotesLogoSvg.ts";
import { LOGO_COLORS } from "../lib/brand/exchangeNotesLogo.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const brand = path.join(root, "public", "brand");

const written = [];

async function write(relativePath, contents) {
  const target = path.join(root, relativePath);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, contents);
  written.push({ relativePath, bytes: contents.length });
}

/**
 * SVG to PNG.
 *
 * `density` is set from the requested size rather than left at the default
 * 72dpi: librsvg rasterises at the document's own size first and then sharp
 * resizes, so a 1024px icon rendered from a 512-unit document at 72dpi is
 * upscaled from 512 and lands soft. Rendering at the right density instead
 * keeps every edge on the curve.
 */
async function png(svg, size, { opaque = false } = {}) {
  const pipeline = sharp(Buffer.from(svg), {
    density: Math.max(72, (size / 512) * 96),
  }).resize(size, size, {
    fit: "contain",
    background: { r: 0, g: 0, b: 0, alpha: 0 },
  });

  /*
   * App icons drop their alpha channel entirely. The artwork is opaque
   * already — it is a filled square — but an icon that merely *happens* to be
   * opaque still carries an alpha channel that iOS and Android will honour if
   * anything ever punches through it, and a maskable icon with a transparent
   * pixel shows a seam inside the OS's crop. Favicons keep their alpha: they
   * are drawn on a tab strip whose colour is not ours.
   */
  return (opaque ? pipeline.removeAlpha() : pipeline)
    .png({ compressionLevel: 9 })
    .toBuffer();
}

/**
 * A .ico holding PNG payloads — the format Vista and everything since reads,
 * and small enough to be worth writing here rather than taking a dependency
 * for. Three sizes, because this file exists for the browsers that will not
 * take app/icon.svg and those are the ones that pick from the ico's table.
 */
async function ico(sizes, svg) {
  const images = await Promise.all(sizes.map((size) => png(svg, size)));

  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // 1 = icon
  header.writeUInt16LE(images.length, 4);

  let offset = 6 + images.length * 16;
  const directory = images.map((image, index) => {
    const entry = Buffer.alloc(16);
    // 0 means 256 in this field; every size we emit is smaller than that.
    entry.writeUInt8(sizes[index] % 256, 0);
    entry.writeUInt8(sizes[index] % 256, 1);
    entry.writeUInt8(0, 2); // palette size, unused for PNG payloads
    entry.writeUInt8(0, 3); // reserved
    entry.writeUInt16LE(1, 4); // colour planes
    entry.writeUInt16LE(32, 6); // bits per pixel
    entry.writeUInt32LE(image.length, 8);
    entry.writeUInt32LE(offset, 12);
    offset += image.length;
    return entry;
  });

  return Buffer.concat([header, ...directory, ...images]);
}

const README = `# Exchange Notes brand assets

Generated by \`npm run generate:brand\`. Do not edit these by hand — the
geometry lives in \`lib/brand/exchangeNotesLogo.ts\` and every file here is
written from it.

The mark is a ~44% wide symbol inside a large field of negative space. That
proportion is part of the identity: do not enlarge it to fill an icon, and do
not shrink the surrounding space.

| Path | What it is |
| --- | --- |
| \`exchange-notes-mark.svg\` | The canonical master. Painted in \`currentColor\`, so it takes the colour of whatever it is placed in. |
| \`light/exchange-notes-mark-light.svg\` | Light-surface logo — \`${LOGO_COLORS.markLight}\`, no canvas. |
| \`dark/exchange-notes-mark-dark.svg\` | Dark-surface logo — \`${LOGO_COLORS.markDark}\`, no canvas. Identical geometry to the light one; only the colour differs. |
| \`monochrome/exchange-notes-black.svg\` | Single-colour pure black, for print and one-ink output. |
| \`monochrome/exchange-notes-white.svg\` | Single-colour pure white, for the same. |
| \`micro/exchange-notes-micro.svg\` | The 16–24px drawing. Same proportions; the catchlight is dropped because below ~24px it lands on under half a pixel. |
| \`app-icon/icon-1024-light.png\` | Master app icon artwork, \`${LOGO_COLORS.canvasLight}\` canvas. Square, no corner mask: the OS rounds it. |
| \`app-icon/icon-1024-dark.png\` | Master app icon artwork, \`${LOGO_COLORS.canvasDark}\` canvas. |
| \`app-icon/icon-512.png\`, \`app-icon/icon-192.png\` | PWA icons, referenced by \`app/manifest.ts\`. |
| \`favicon/favicon.svg\` | The micro mark on transparency, switching ink with \`prefers-color-scheme\`. Shipped as \`app/icon.svg\`. |
| \`favicon/favicon-32.png\`, \`favicon/favicon-16.png\` | Raster fallbacks, also bundled into \`app/favicon.ico\`. |

Also written outside this directory, from the same geometry:
\`app/icon.svg\`, \`app/apple-icon.png\`, \`app/favicon.ico\`.

## Why there is no separate maskable file

The manifest's \`maskable\` entry points at \`app-icon/icon-512.png\`, the same
file its \`any\` entry uses. A maskable icon has to be opaque to every edge and
keep its artwork inside the platform's crop; this artwork is a full-bleed
opaque square with no corner mask of its own, and the mark sits at 44% of the
canvas — well inside every common launcher mask. A second file would be the
same bytes under another name.

## Why there is no PDF master

A vector PDF is a design-tool export, and every route to one from this script
would rasterise the mark on the way — which is the one thing a master must not
do. Open \`exchange-notes-mark.svg\` in Illustrator, Figma or Affinity and
export the PDF from there.
`;

async function main() {
  await mkdir(brand, { recursive: true });

  // The canonical master. currentColor, full detail, no canvas.
  await write("public/brand/exchange-notes-mark.svg", renderLogoSvg());

  await write(
    "public/brand/light/exchange-notes-mark-light.svg",
    renderLogoSvg({ color: LOGO_COLORS.markLight }),
  );
  await write(
    "public/brand/dark/exchange-notes-mark-dark.svg",
    renderLogoSvg({ color: LOGO_COLORS.markDark }),
  );

  await write(
    "public/brand/monochrome/exchange-notes-black.svg",
    renderLogoSvg({ color: "#000000" }),
  );
  await write(
    "public/brand/monochrome/exchange-notes-white.svg",
    renderLogoSvg({ color: "#ffffff" }),
  );

  await write(
    "public/brand/micro/exchange-notes-micro.svg",
    renderLogoSvg({ tier: "micro", size: 64 }),
  );

  const iconLight = renderAppIconSvg({ mode: "light" });
  const iconDark = renderAppIconSvg({ mode: "dark" });

  await write(
    "public/brand/app-icon/icon-1024-light.png",
    await png(iconLight, 1024, { opaque: true }),
  );
  await write(
    "public/brand/app-icon/icon-1024-dark.png",
    await png(iconDark, 1024, { opaque: true }),
  );

  await write(
    "public/brand/app-icon/icon-192.png",
    await png(iconLight, 192, { opaque: true }),
  );
  /*
   * One 512 serves the manifest's "any" and "maskable" entries both — see the
   * README. The artwork is opaque to every edge with no corner mask of its
   * own, and the mark sits inside every common crop at 44% of the canvas, so
   * a second file would only be the same bytes under another name.
   */
  await write(
    "public/brand/app-icon/icon-512.png",
    await png(iconLight, 512, { opaque: true }),
  );

  const favicon = renderFaviconSvg();
  await write("public/brand/favicon/favicon.svg", favicon);
  await write("public/brand/favicon/favicon-32.png", await png(favicon, 32));
  await write("public/brand/favicon/favicon-16.png", await png(favicon, 16));

  await write("public/brand/README.md", README);

  /*
   * The three files Next serves from app/ by file convention. They are copies
   * of assets above rather than a second drawing — same geometry, same run.
   * This is what §19 means by integrating with the App Router's own icon
   * conventions instead of standing up a competing set under /public.
   */
  await write("app/icon.svg", favicon);
  await write("app/apple-icon.png", await png(iconLight, 180, { opaque: true }));
  await write("app/favicon.ico", await ico([16, 32, 48], favicon));

  const total = written.reduce((sum, file) => sum + file.bytes, 0);
  for (const file of written) {
    console.log(
      `  ${file.relativePath.padEnd(52)} ${String(file.bytes).padStart(8)} bytes`,
    );
  }
  console.log(`\n${written.length} files, ${(total / 1024).toFixed(1)} KB.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
