import type { InterfaceLanguage } from "@/lib/appPreferences";

type Copy = { pause: string; resume: string; gather: string; hint: string; feed: string; listen: string; stop: string; loading: string; error: string; library: string; collection: string };
export const floatingCopy: Record<InterfaceLanguage, Copy> = {
  english: { pause: "Pause floating cookies", resume: "Resume floating cookies", gather: "Gather and scatter cookies", hint: "Tap a cookie to discover a word. Drag it to Yumi to feed her. Hold the background to gather them.", feed: "Feed Yumi", listen: "Listen", stop: "Stop", loading: "Preparing audio", error: "Audio is unavailable. Tap to try again.", library: "Open word", collection: "From your collection" },
  "traditional-chinese": { pause: "暫停漂浮餅乾", resume: "繼續漂浮餅乾", gather: "聚集並散開餅乾", hint: "點餅乾看字卡，拖給 Yumi 餵食。長按空白處讓餅乾聚集。", feed: "餵給 Yumi", listen: "聽發音", stop: "停止發音", loading: "準備發音中", error: "目前無法播放，請再點一次。", library: "打開單字", collection: "來自你的收藏" },
  spanish: { pause: "Pausar galletas", resume: "Reanudar galletas", gather: "Reunir y dispersar galletas", hint: "Toca una galleta para ver la palabra. Arrástrala a Yumi para alimentarla. Mantén pulsado el fondo para reunirlas.", feed: "Alimentar a Yumi", listen: "Escuchar", stop: "Detener", loading: "Preparando audio", error: "Audio no disponible. Toca para reintentar.", library: "Abrir palabra", collection: "De tu colección" },
  french: { pause: "Suspendre les biscuits", resume: "Animer les biscuits", gather: "Rassembler et disperser les biscuits", hint: "Touchez un biscuit pour voir le mot. Glissez-le vers Yumi pour la nourrir. Maintenez le fond pour les rassembler.", feed: "Nourrir Yumi", listen: "Écouter", stop: "Arrêter", loading: "Préparation audio", error: "Audio indisponible. Touchez pour réessayer.", library: "Ouvrir le mot", collection: "Votre collection" },
  italian: { pause: "Ferma i biscotti", resume: "Anima i biscotti", gather: "Riunisci e spargi i biscotti", hint: "Tocca un biscotto per vedere la parola. Trascinalo verso Yumi per nutrirla. Tieni premuto lo sfondo per riunirli.", feed: "Nutri Yumi", listen: "Ascolta", stop: "Ferma", loading: "Preparazione audio", error: "Audio non disponibile. Tocca per riprovare.", library: "Apri parola", collection: "Dalla tua raccolta" },
};
