-- Evaluate auth.uid() once per query instead of once per row.
--
-- A bare auth.uid() inside an RLS policy is re-evaluated for every row the
-- query touches. Wrapped as (select auth.uid()) it becomes an InitPlan that
-- Postgres runs a single time and reuses. Same value, same result, same rows —
-- the difference is only how many times the function is called, which is why
-- this is safe to apply wholesale. The performance advisor flagged all 71.
--
-- It matters most where rows accumulate. Reading a thread scans messages,
-- message_receipts, message_user_states and hidden_messages; at a thousand
-- messages that was a thousand redundant calls per policy per query. Vocabulary
-- and collections have the same shape and the most policies of anything here.
--
-- These are ALTER POLICY, not drop-and-recreate: the policy name, the command,
-- the roles it applies to and its permissive/restrictive nature all stay
-- exactly as they were, and only the expression is rewritten. Nothing here
-- widens or narrows who can see what.
--
-- The statements were generated by Postgres itself from pg_policies via
-- regexp_replace, not written by hand, and the file was checksummed against
-- that generated output before being committed (md5 77d34b2a37e11d8702633c99549d310b).

alter policy "Users can add members to conversations they're in" on public.conversation_members
  with check (((user_id = (select auth.uid())) OR is_conversation_member(conversation_id)));
alter policy "Users can update their own membership" on public.conversation_members
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
alter policy "Users can update their own read state" on public.conversation_members
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
alter policy "Authenticated users can create conversations" on public.conversations
  with check (((select auth.uid()) IS NOT NULL));
alter policy "Users can delete their own device tokens" on public.device_tokens
  using ((user_id = (select auth.uid())));
alter policy "Users can register their own device tokens" on public.device_tokens
  with check ((user_id = (select auth.uid())));
alter policy "Users can update their own device tokens" on public.device_tokens
  using ((user_id = (select auth.uid())))
  with check ((user_id = (select auth.uid())));
alter policy "Users can view their own device tokens" on public.device_tokens
  using ((user_id = (select auth.uid())));
alter policy "Receiver can respond to a request" on public.friend_requests
  using ((receiver_id = (select auth.uid())))
  with check ((receiver_id = (select auth.uid())));
alter policy "Sender or receiver can remove a request" on public.friend_requests
  using (((sender_id = (select auth.uid())) OR (receiver_id = (select auth.uid()))));
alter policy "Users can send requests" on public.friend_requests
  with check ((sender_id = (select auth.uid())));
alter policy "Users can update their own friend requests" on public.friend_requests
  using ((((select auth.uid()) = sender_id) OR ((select auth.uid()) = receiver_id)))
  with check ((((select auth.uid()) = sender_id) OR ((select auth.uid()) = receiver_id)));
alter policy "Users can view their own requests" on public.friend_requests
  using (((sender_id = (select auth.uid())) OR (receiver_id = (select auth.uid()))));
alter policy "Users can create a friendship they're part of" on public.friendships
  with check (((user_one_id = (select auth.uid())) OR (user_two_id = (select auth.uid()))));
alter policy "Users can create friendships they're part of" on public.friendships
  with check ((((select auth.uid()) = user_one_id) OR ((select auth.uid()) = user_two_id)));
alter policy "Users can delete friendships they're part of" on public.friendships
  using ((((select auth.uid()) = user_one_id) OR ((select auth.uid()) = user_two_id)));
alter policy "Users can view their friendships" on public.friendships
  using ((((select auth.uid()) = user_one_id) OR ((select auth.uid()) = user_two_id)));
alter policy "Users can view their own friendships" on public.friendships
  using (((user_one_id = (select auth.uid())) OR (user_two_id = (select auth.uid()))));
alter policy "Users can hide messages for themselves" on public.hidden_messages
  with check (((select auth.uid()) = user_id));
alter policy "Users can view their own hidden messages" on public.hidden_messages
  using (((select auth.uid()) = user_id));
alter policy "Users can create their own receipt" on public.message_receipts
  with check (((user_id = (select auth.uid())) AND (EXISTS ( SELECT 1
   FROM messages m
  WHERE ((m.id = message_receipts.message_id) AND is_conversation_member(m.conversation_id))))));
alter policy "Users can update their own receipt" on public.message_receipts
  using ((user_id = (select auth.uid())))
  with check ((user_id = (select auth.uid())));
alter policy "Users can create their own message states" on public.message_user_states
  with check ((((select auth.uid()) = user_id) AND (EXISTS ( SELECT 1
   FROM messages m
  WHERE ((m.id = message_user_states.message_id) AND is_conversation_member(m.conversation_id))))));
alter policy "Users can delete their own message states" on public.message_user_states
  using (((select auth.uid()) = user_id));
alter policy "Users can update their own message states" on public.message_user_states
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
alter policy "Users can view their own message states" on public.message_user_states
  using (((select auth.uid()) = user_id));
alter policy "Members can send messages" on public.messages
  with check (((sender_id = (select auth.uid())) AND is_conversation_member(conversation_id)));
alter policy "Users can delete own messages" on public.messages
  using (((select auth.uid()) = sender_id));
alter policy "Users create their own notes" on public.notes
  with check (((select auth.uid()) = user_id));
alter policy "Users delete their own notes" on public.notes
  using (((select auth.uid()) = user_id));
alter policy "Users read their own notes" on public.notes
  using (((select auth.uid()) = user_id));
alter policy "Users update their own notes" on public.notes
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
alter policy "Users can update their own notification preferences" on public.notification_preferences
  using ((user_id = (select auth.uid())))
  with check ((user_id = (select auth.uid())));
alter policy "Users can upsert their own notification preferences" on public.notification_preferences
  with check ((user_id = (select auth.uid())));
alter policy "Users can view their own notification preferences" on public.notification_preferences
  using ((user_id = (select auth.uid())));
alter policy "Conversation members can create notifications for each other" on public.notifications
  with check (((actor_id IS NULL) OR (actor_id = (select auth.uid()))));
alter policy "Users can delete their own notifications" on public.notifications
  using ((user_id = (select auth.uid())));
alter policy "Users can update their own notifications" on public.notifications
  using ((user_id = (select auth.uid())))
  with check ((user_id = (select auth.uid())));
alter policy "Users can view their own notifications" on public.notifications
  using ((user_id = (select auth.uid())));
alter policy "Users can insert own profile" on public.profiles
  with check ((id = (select auth.uid())));
alter policy "Users can update own profile" on public.profiles
  using ((id = (select auth.uid())))
  with check ((id = (select auth.uid())));
alter policy "Users can view own profile" on public.profiles
  using ((id = (select auth.uid())));
alter policy "Users can insert their own pronunciation practice state" on public.pronunciation_practice_state
  with check (((select auth.uid()) = user_id));
alter policy "Users can read their own pronunciation practice state" on public.pronunciation_practice_state
  using (((select auth.uid()) = user_id));
alter policy "Users can update their own pronunciation practice state" on public.pronunciation_practice_state
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
alter policy "Users can delete own saved news" on public.saved_news_articles
  using (((select auth.uid()) = user_id));
alter policy "Users can save own news" on public.saved_news_articles
  with check (((select auth.uid()) = user_id));
alter policy "Users can update own saved news" on public.saved_news_articles
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
alter policy "Users can view own saved news" on public.saved_news_articles
  using (((select auth.uid()) = user_id));
alter policy "Users add own collection items" on public.vocabulary_collection_items
  with check (((EXISTS ( SELECT 1
   FROM vocabulary_collections c
  WHERE ((c.id = vocabulary_collection_items.collection_id) AND (c.user_id = (select auth.uid()))))) AND (EXISTS ( SELECT 1
   FROM vocabulary_items v
  WHERE ((v.id = vocabulary_collection_items.vocabulary_item_id) AND (v.user_id = (select auth.uid())))))));
alter policy "Users can add to their own collections" on public.vocabulary_collection_items
  with check ((EXISTS ( SELECT 1
   FROM vocabulary_collections c
  WHERE ((c.id = vocabulary_collection_items.collection_id) AND (c.user_id = (select auth.uid()))))));
alter policy "Users can remove from their own collections" on public.vocabulary_collection_items
  using ((EXISTS ( SELECT 1
   FROM vocabulary_collections c
  WHERE ((c.id = vocabulary_collection_items.collection_id) AND (c.user_id = (select auth.uid()))))));
alter policy "Users can view their own collection items" on public.vocabulary_collection_items
  using ((EXISTS ( SELECT 1
   FROM vocabulary_collections c
  WHERE ((c.id = vocabulary_collection_items.collection_id) AND (c.user_id = (select auth.uid()))))));
alter policy "Users remove own collection items" on public.vocabulary_collection_items
  using ((EXISTS ( SELECT 1
   FROM vocabulary_collections c
  WHERE ((c.id = vocabulary_collection_items.collection_id) AND (c.user_id = (select auth.uid()))))));
alter policy "Users view own collection items" on public.vocabulary_collection_items
  using ((EXISTS ( SELECT 1
   FROM vocabulary_collections c
  WHERE ((c.id = vocabulary_collection_items.collection_id) AND (c.user_id = (select auth.uid()))))));
alter policy "Users can create their own collections" on public.vocabulary_collections
  with check (((select auth.uid()) = user_id));
alter policy "Users can delete their own collections" on public.vocabulary_collections
  using (((select auth.uid()) = user_id));
alter policy "Users can update their own collections" on public.vocabulary_collections
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
alter policy "Users can view their own collections" on public.vocabulary_collections
  using (((select auth.uid()) = user_id));
alter policy "Users manage own collections" on public.vocabulary_collections
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
alter policy "Users can delete own vocabulary" on public.vocabulary_items
  using (((select auth.uid()) = user_id));
alter policy "Users can insert own vocabulary" on public.vocabulary_items
  with check (((select auth.uid()) = user_id));
alter policy "Users can update own vocabulary" on public.vocabulary_items
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
alter policy "Users can view own vocabulary" on public.vocabulary_items
  using (((select auth.uid()) = user_id));
alter policy "Users can create their own web push subscriptions" on public.web_push_subscriptions
  with check ((user_id = (select auth.uid())));
alter policy "Users can delete their own web push subscriptions" on public.web_push_subscriptions
  using ((user_id = (select auth.uid())));
alter policy "Users can update their own web push subscriptions" on public.web_push_subscriptions
  using ((user_id = (select auth.uid())))
  with check ((user_id = (select auth.uid())));
alter policy "Users can view their own web push subscriptions" on public.web_push_subscriptions
  using ((user_id = (select auth.uid())));
alter policy "Users can insert their own pet state" on public.yumi_pet_state
  with check (((select auth.uid()) = user_id));
alter policy "Users can read their own pet state" on public.yumi_pet_state
  using (((select auth.uid()) = user_id));
alter policy "Users can update their own pet state" on public.yumi_pet_state
  using (((select auth.uid()) = user_id))
  with check (((select auth.uid()) = user_id));
